/**********************************/
/* Table Name: 게시판 */
/**********************************/

DROP TABLE BOARD CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE BOARD;

DROP SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD(
    BOARDNO        NUMBER(10)       NOT NULL PRIMARY KEY,
    ACCOUNTNO      NUMBER(10)       NULL,
    MANAGERNO      NUMBER(10)       NULL,
    CRUDCATENO     NUMBER(10)       NULL,
    BTITLE         VARCHAR2(20)     NOT NULL,
    BCONTENT       CLOB             NOT NULL,
    BDATE          DATE             NOT NULL,
    BPASSWD        VARCHAR2(200)    NOT NULL,
    BTAG           VARCHAR2(100)    NULL,
    BPHOTO         VARCHAR2(100)    NULL,
    BPHOTOSAVED    VARCHAR2(100)    NULL,
    BTHUMB         VARCHAR2(100)    NULL,
    BSIZE          NUMBER(10)       DEFAULT 0 NULL,
    BREPLYCNT      NUMBER(10)       DEFAULT 0 NULL,
    BVIEW          NUMBER(7)        DEFAULT 0 NULL,
    BRECOM         NUMBER(7)        DEFAULT 0 NULL,
    BYOUTUBE       VARCHAR2(1000)   NULL,
    BVISIBLE       CHAR(1)          DEFAULT 'N' NOT NULL,
    TAGNO          NUMBER(10)       NULL,
    FOREIGN KEY (ACCOUNTNO) REFERENCES ACCOUNT (ACCOUNTNO),
    FOREIGN KEY (MANAGERNO) REFERENCES MANAGER (MANAGERNO),
    FOREIGN KEY (CRUDCATENO) REFERENCES CRUDCATE (CRUDCATENO)
);


COMMENT ON TABLE BOARD is '게시판';
COMMENT ON COLUMN BOARD.BOARDNO is '게시판번호';
COMMENT ON COLUMN BOARD.BTITLE is '게시판 제목';
COMMENT ON COLUMN BOARD.BCONTENT is '게시판 내용';
COMMENT ON COLUMN BOARD.BDATE is '게시판 등록일';
COMMENT ON COLUMN BOARD.BPASSWD is '게시판 비밀번호';
COMMENT ON COLUMN BOARD.BTAG is '게시판 태그';
COMMENT ON COLUMN BOARD.BPHOTO is '게시판 이미지';
COMMENT ON COLUMN BOARD.BPHOTOSAVED is '저장된 게시판 이미지';
COMMENT ON COLUMN BOARD.BTHUMB is '게시판 썸네일';
COMMENT ON COLUMN BOARD.BSIZE is '파일 사이즈';
COMMENT ON COLUMN BOARD.BREPLYCNT is '댓글수';
COMMENT ON COLUMN BOARD.BVIEW is '게시판 조회수';
COMMENT ON COLUMN BOARD.BRECOM is '게시판 추천수';
COMMENT ON COLUMN BOARD.BYOUTUBE is '게시판 유튜브';
COMMENT ON COLUMN BOARD.BVISIBLE is '게시판 출력모드';
COMMENT ON COLUMN BOARD.ACCOUNTNO is '유저 번호';
COMMENT ON COLUMN BOARD.MANAGERNO is '관리자번호';
COMMENT ON COLUMN BOARD.TAGNO is '분류번호';
COMMENT ON COLUMN BOARD.CRUDCATENO is '카테고리번호';

-- SEQUENCE
CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999999999
    CACHE 2
    NOCYCLE;

SELECT CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'BOARD'
AND CONSTRAINT_TYPE = 'R';

ALTER TABLE BOARD DROP CONSTRAINT <sysid>
ALTER TABLE BOARD DROP CONSTRAINT <sysid>

ALTER TABLE BOARD
ADD CONSTRAINT fk_board_accountno
FOREIGN KEY (ACCOUNTNO)
REFERENCES ACCOUNT (ACCOUNTNO)
ON DELETE SET NULL;

ALTER TABLE BOARD
ADD CONSTRAINT fk_board_managerno
FOREIGN KEY (MANAGERNO)
REFERENCES MANAGER (MANAGERNO)
ON DELETE SET NULL;