/**********************************/
/* Table Name: 북마크 */
/**********************************/

DROP TABLE BOOKMARK CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE BOOKMARK;

DROP SEQUENCE BOOKMARK_SEQ;

CREATE TABLE BOOKMARK(
    BOOKMARKNO   NUMBER(10)       NOT NULL PRIMARY KEY,
    ACCOUNTNO    NUMBER(10)       NOT NULL,
    BOARDNO    NUMBER(10)       NOT NULL,
    BOOKMARKURL  VARCHAR2(200)    NOT NULL, 
    BMDATE                       		DATE		 NOT NULL,    
    FOREIGN KEY (ACCOUNTNO) REFERENCES ACCOUNT (ACCOUNTNO),
    FOREIGN KEY (BOARDNO) REFERENCES BOARD (BOARDNO),
    CONSTRAINT UQ_BOARDNO UNIQUE (BOARDNO) -- 보드 번호에 대한 고유성 제약 조건 추가
);

COMMENT ON TABLE BOOKMARK IS '북마크';
COMMENT ON COLUMN BOOKMARK.BOOKMARKNO IS '북마크 번호';
COMMENT ON COLUMN BOOKMARK.ACCOUNTNO IS '유저 번호';
COMMENT ON COLUMN BOOKMARK.BOARDNO IS '게시판 번호';
COMMENT ON COLUMN BOOKMARK.BOOKMARKURL IS '북마크 URL';
COMMENT ON COLUMN BOOKMARK.BMDATE IS '북마크 등록일';

CREATE SEQUENCE BOOKMARK_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999999999
    CACHE 2
    NOCYCLE;
    
COMMIT;