CREATE TABLE AI_SEARCH(
		SEARCHNO                      		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		IMG_SEARCH                    		VARCHAR2(100)		 NULL ,
		IMG_SEARCH_SAVE               		VARCHAR2(100)		 NULL ,
		IMG_SEARCH_THUMB              		VARCHAR2(100)		 NULL ,
		IMG_SEARCH_SIZE               		NUMBER(10)		 NULL ,
		TEXT_SEARCH                   		CLOB		 NULL ,
		ACCOUNTNO                     		NUMBER(10)		 NULL ,
		ANSWERNO                      		NUMBER(10)		 NULL ,
  FOREIGN KEY (ACCOUNTNO) REFERENCES ACCOUNT (ACCOUNTNO)
);

COMMENT ON TABLE AI_SEARCH is 'AI 검색';
COMMENT ON COLUMN AI_SEARCH.SEARCHNO is '검색 번호';
COMMENT ON COLUMN AI_SEARCH.IMG_SEARCH is '검색 이미지';
COMMENT ON COLUMN AI_SEARCH.IMG_SEARCH_SAVE is '저장된 검색 이미지';
COMMENT ON COLUMN AI_SEARCH.IMG_SEARCH_THUMB is '검색 이미지 썸네일';
COMMENT ON COLUMN AI_SEARCH.IMG_SEARCH_SIZE is '검색 이미지 사이즈';
COMMENT ON COLUMN AI_SEARCH.TEXT_SEARCH is '검색 내용';
COMMENT ON COLUMN AI_SEARCH.ACCOUNTNO is '유저 번호';
COMMENT ON COLUMN AI_SEARCH.ANSWERNO is '답변 번호';

DROP SEQUENCE AI_SEARCH_SEQ;

CREATE SEQUENCE AI_SEARCH_SEQ
    START WITH 1         -- 시작 번호
    INCREMENT BY 1       -- 증가값
    MAXVALUE 9999999999  -- 최대값: 9999999999 --> NUMBER(10) 대응
    CACHE 2              -- 2번은 메모리에서만 계산
    NOCYCLE;             -- 다시 1부터 생성되는 것을 방지
INSERT INTO AI_SEARCH (SEARCHNO, IMG_SEARCH, IMG_SEARCH_SAVE, IMG_SEARCH_THUMB, IMG_SEARCH_SIZE, TEXT_SEARCH, ACCOUNTNO, ANSWERNO)
VALUES (AI_SEARCH_SEQ.NEXTVAL, '이미지1.jpg', '이미지1_saved.jpg', '이미지1_thumb.jpg', 1024, '텍스트 검색 내용 1', 1, 1);


/**********************************/
/* Table Name: AI 답변 */
/**********************************/

CREATE TABLE AI_ANSWER(
		ANSWERNO                      		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		TEXT_ANSWER                   		CLOB		 NULL ,
		SEARCHNO                      		NUMBER(10)		 NULL ,
  FOREIGN KEY (SEARCHNO) REFERENCES AI_SEARCH (SEARCHNO)
);

COMMENT ON TABLE AI_ANSWER is 'AI 답변';
COMMENT ON COLUMN AI_ANSWER.ANSWERNO is '답변 번호';
COMMENT ON COLUMN AI_ANSWER.TEXT_ANSWER is '답변 내용';
COMMENT ON COLUMN AI_ANSWER.SEARCHNO is '검색 번호';
