DROP TABLE L_RECOM
DROP SEQUENCE  L_RECOM_SEQ

-- 테이블 생성
CREATE TABLE L_RECOM (
    L_NO       NUMBER(10)       NOT NULL PRIMARY KEY,
    ACCOUNTNO  NUMBER(10)       NOT NULL,
    L_MENU     VARCHAR2(255)    NOT NULL,
    L_RECIPE   VARCHAR2(255)    NULL,
    L_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (ACCOUNTNO) REFERENCES ACCOUNT (ACCOUNTNO)
);

-- 시퀀스 생성
CREATE SEQUENCE L_RECOM_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999999999
    CACHE 20
    NOCYCLE;